# .goreleaser.yml
project_name: game_client

before:
  hooks:
    - go mod tidy

builds:
  - id: game_client
    binary: game_client
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - game_client
    format: tar.gz
    format_overrides:
      - goos: darwin
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: yourusername
    name: o_and_m_online
  draft: true
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

universal_binaries:
  - id: game_client
    ids:
      - game_client
    replace: true
    name_template: "game_client"

# macOS specific configuration
nfpms:
  - maintainer: Olive & Millie <support@oliveandmillie.com>
    description: Olive & Millie's Game Room - Online Multiplayer Games
    homepage: https://oliveandmillie.com
    license: Proprietary
    formats:
      - apk
      - deb
      - rpm